brokeraddress: tcp://192.168.68.34:1883
clientid: iot_server_1
password: test123
mqtttopic: dht/temperature_humidity
mqttqos: 0
influxdbaddress: http://192.168.68.34:8086
influxdbtoken: J14d03Sog_JjCVLisAJCwmvugq6o7vKjF6Jidz9pH1t4iMthJWSZDjOn1Mkb2eev5H_mnxjkpWzGLCa944leyg==
dborganization: admin
dbbucket: admin