brokeraddress: tcp://192.168.2.160:1883
clientid: iot_server_1
password: test123
mqtttopic: dht/temperature_humidity
mqttqos: 0
influxdbaddress: http://192.168.2.160:8086
influxdbtoken: _S6l8D1i8dDoAFNnMDCwM11I7AaQUzqeVmAEQEwC_6ljNFrAyOTs9nxx-N7nG-i6ogH2_20yq_iW_4g8p5hYqg==